# Generated by Django 5.2.2 on 2025-09-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_customuser_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='citizenship_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='citizenship number'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'Normal User'), ('guide', 'Tour Guide')], default='user', max_length=10),
        ),
    ]
