# Generated by Django 5.2.2 on 2025-09-24 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destinationtype',
            name='icon',
        ),
    ]
