# Generated by Django 5.2.2 on 2025-09-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_destinationtype_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='citizenship_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='citizenship number'),
        ),
    ]
