# Generated by Django 5.2.2 on 2025-06-14 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_favorites'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Member', 'verbose_name_plural': 'Members'},
        ),
    ]
