# Generated by Django 5.2.2 on 2025-09-24 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_activity_description_activity_image_food_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='price_range',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='activity',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='food',
            name='price_range',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='food',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='place',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='price_range',
            field=models.FloatField(default=100.0),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
