# Generated by Django 5.2.2 on 2025-09-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_activity_price_range_activity_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='price_range',
            field=models.CharField(max_length=50),
        ),
    ]
