# Generated by Django 5.2.2 on 2025-09-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_hotel_price_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='price_range',
            field=models.FloatField(default=100.0),
        ),
    ]
